version: '3.9'

services:

  infirmary-db:
    image: oscarfonts/h2
    container_name: infirmary-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8084
    networks:
      - my_local_network


  laboratory-db:     
    image: oscarfonts/h2
    container_name: laboratory-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8083
    networks:
      - my_local_network
      
  activemq:
    image: rmohr/activemq::5.15.9
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - my_local_network


  infirmary-service:
    build: 
     context: ./infirmary
     dockerfile: Dockerfile
    restart: always
    container_name: infirmary
    ports:
      - "8084:8084"
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      #- ACTIVEMQ_URL=tcp://localhost:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/infirmary-service
    networks:
      - my_local_network
    depends_on:
      - infirmary-db
      - activemq
      
  laboratory-service:
    build: 
     context: ./laboratory
     dockerfile: Dockerfile
    restart: always
    container_name: laboratory
    ports:
      - "8083:8083"
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      #- ACTIVEMQ_URL=tcp://localhost:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/laboratory-service
    networks:
      - my_local_network
    depends_on:
      - laboratory-db
      - activemq

  
networks:
  my_local_network:
    external: true