version: '3.9'

services:

  patients-db:
    image: oscarfonts/h2
    container_name: patients-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8081
    networks:
      - my_local_network
      
      
  activemq:
    image: rmohr/activemq::5.15.9
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - my_local_network
      
  patients-service:
    build: 
     context: ./patients
     dockerfile: Dockerfile
    restart: always
    container_name: patients
    ports:
      - "8081:8081"
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      #- ACTIVEMQ_URL=tcp://localhost:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/patients-service
    networks:
      - my_local_network
    depends_on:
      - patients-db
      - activemq
  


  employees-db:     
    image: oscarfonts/h2
    container_name: employees-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8080
    networks:
      - my_local_network


  
      
      
  employees-service:
    build: 
     context: ./employees
     dockerfile: Dockerfile
    restart: always
    container_name: employees
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/employees-service
    networks:
      - my_local_network
    depends_on:
      - employees-db

  

networks:
  my_local_network:
    name : my_local_network
