version: '3.9'

services:

  patients-db:
    image: oscarfonts/h2
    container_name: patients-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8081
    networks:
      - my_local_network
      
      
  activemq:
    build: 
      context: ./activeMQ
      dockerfile: Dockerfile
    restart: always
    container_name: activemq
    ports:
      - "8079:8079"
      - "8078:8078"
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./activemq/data:/data
      - ./activemq/conf:/conf
      - ./activemq/logs:/logs
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - my_local_network
    


      
  patients-service:
    build: 
     context: ./patients
     dockerfile: Dockerfile
    restart: always
    container_name: patients
    ports:
      - "8081:8081"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/patients-service
    networks:
      - my_local_network
    depends_on:
      - patients-db
      - activemq
  


  employees-db:     
    image: oscarfonts/h2
    container_name: employees-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8080
    networks:
      - my_local_network

      
  employees-service:
    build: 
     context: ./employees
     dockerfile: Dockerfile
    restart: always
    container_name: employees
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/employees-service
    networks:
      - my_local_network
    depends_on:
      - employees-db
      
      
      
  infirmary-db:
    image: oscarfonts/h2
    container_name: infirmary-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8084
    networks:
      - my_local_network
      
  infirmary-service:
    build: 
     context: ./infirmary
     dockerfile: Dockerfile
    restart: always
    container_name: infirmary
    ports:
      - "8084:8084"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/infirmary-service
    networks:
      - my_local_network
    depends_on:
      - infirmary-db
      - activemq
      
      
  laboratory-db:     
    image: oscarfonts/h2
    container_name: laboratory-db
    restart: always
    volumes:
      - ./h2:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8083
    networks:
      - my_local_network
      
  laboratory-service:
    build: 
     context: ./laboratory
     dockerfile: Dockerfile
    restart: always
    container_name: laboratory
    ports:
      - "8083:8083"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/laboratory-service
    networks:
      - my_local_network
    depends_on:
      - laboratory-db
      - activemq

  

networks:
  my_local_network:
    name : my_local_network